# Generated by Django 5.2.7 on 2025-12-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('question_text', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=300)),
                ('incorrect_answers', models.JSONField()),
                ('difficulty', models.CharField(max_length=50)),
                ('api_source', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
