# Generated by Django 4.2.25 on 2025-12-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_achievement_flashcard_studyroom_task_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_time_studying',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
