# Generated by Django 5.2.7 on 2025-12-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userstats_level_alter_userstats_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
